name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32
      
    - name: Install Rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Check out source code
      uses: actions/checkout@v6.0.2

    - name: Check
      run: cargo check

    - name: Build-linux
      run: cargo build --release --target x86_64-unknown-linux-musl
      
    - name: tar Build-linux
      run: tar -czf target/x86_64-unknown-linux-musl.tar.gz target/x86_64-unknown-linux-musl
      
    - name: Build-windows
      run: cargo build --release --target x86_64-pc-windows-gnu
      
    - name: Install zip
      run: sudo apt-get install --yes --no-install-recommends zip
      
    - name: zip Build-windows
      run: zip -r target/x86_64-pc-windows-gnu.zip target/x86_64-pc-windows-gnu
      
    - name: Release
      id: new-release
      uses: softprops/action-gh-release@v3
      with:
        name: Release ${{ github.run_number }}
        tag_name: ${{ github.run_number }}
        working_directory: target
        files: |
          x86_64-pc-windows-gnu.zip
          x86_64-unknown-linux-musl.tar.gz
